"""Shared type aliases."""
from typing import Protocol, Tuple, Any, Dict
import numpy as np


class SubstrateProtocol(Protocol):
    def reset(self, seed: int): ...
    def step(self, state, action=None): ...
    def render(self, state, out_dir, step_idx: int): ...
    def serialize(self, state) -> bytes: ...
    def deserialize(self, data: bytes): ...
    def metrics(self, state) -> Dict[str, float]: ...


Array2D = np.ndarray
